### ISSUE TITLE
XilogNG

### ISSUE THREAD

**Issue by robeisenrich** [Primayer/XilogApiDocs#3]
From my ATRIUM account, I have 2 active NG Xilog loggers in my IOT Demo Group. When I use the getsites endpoint for the associated token it returns an empty data set. Does this documentation/endpoints still work with the new xilog ng / ATRIUM?

**Comment by James-Goodbourn** [comment]
Hello @robeisenrich this documentation is only for PrimeWeb, and does not work for Xilog NG. The new documentation for Atrium can be found here:
https://github.com/Primayer/XilogDataApiDocs

Hope that helps
